
public class ExceptionDemo 
{

	public static void main(String[] args)
	{
		
		try
		{
		int a=10, b=6, c;
		System.out.println("before");
		c=a/(b-6);
		System.out.println("after");
		}
		catch(Exception e)
		{
			System.out.println("divided by zero error");
		}

	}

}
